### ISSUE TITLE
Can you add a simple example for using this little library

### ISSUE THREAD

**Issue by orklann** [dhess/c-ringbuf#12]
What I want is:

1. Produce bytes to the ring buffer
2. Consume some bytes of the ring buffer

However, I am not sure how to use it. Is there any simple example?

**Comment by dhess** [comment]
Yes, see my echo client/server project: https://github.com/dhess/echoev

It has an embedded version of the ring buffer code from this project. The version contained there is slightly older than the code here, but the key functionality is the same.

**Comment by orklann** [comment]
Ok, thank you for the help.
